
export const placeholderIngredients = [
    {
        name: 'Chicken',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 141,
        proteins: 30.1,
        carbs: 0.1,
        fats: 2,
    },
    {
        name: 'Tomatoes',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 19,
        proteins: 0.86,
        carbs: 2.49,
        fats: 0.26,
    },
    {
        name: 'Red Peppers',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 29,
        proteins: 0.92,
        carbs: 2.36,
        fats: 0.1,
    },
    {
        name: 'Mushrooms',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 8,
        proteins: 1,
        carbs: 0.5,
        fats: 0.1,
    },
    {
        name: 'Lord Tomato Sauce Basilic',
        unit: 'jar',
        gramsPerUnit: 660,
        calories: 415,
        proteins: 9.9,
        carbs: 47.5,
        fats: 19.8,
    },
    {
        name: 'Cheddar',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 416,
        proteins: 25,
        carbs: 2,
        fats: 34.5,
    },   
    {
        name: 'Onion',
        unit: 'item',
        gramsPerUnit: 84,
        calories: 41,
        proteins: 1.1,
        carbs: 10,
        fats: 0.1,
    },
    {
        name: 'Pork Shoulders',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 270,
        proteins: 7.2,
        carbs: 1,
        fats: 17.3,
    },
    {
        name: 'Banana',
        unit: 'item',
        gramsPerUnit: 120,
        calories: 105,
        proteins: 1.3,
        carbs: 27,
        fats: 0.4,
    },
    {
        name: 'Eggs',
        unit: 'item',
        gramsPerUnit: 57,
        calories: 72,
        proteins: 6.3,
        carbs: 0.4,
        fats: 4.8,
    },
    {
        name: 'Pre-cooked Bread',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 265,
        proteins: 8.5,
        carbs: 54.7,
        fats: 1,
    },
    {
        name: 'Proscuitto',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 249,
        proteins: 28,
        carbs: 0.1,
        fats: 15,
    },
    {
        name: 'Calippo Mini Orange',
        unit: 'item',
        gramsPerUnit: 84,
        calories: 75,
        proteins: 0.4,
        carbs: 17.6,
        fats: 0.4,
    },
    {
        name: 'Rice',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 161,
        proteins: 3,
        carbs: 34,
        fats: 14,
    },
    {
        name: 'Milk',
        unit: '100ml',
        gramsPerUnit: 103,
        calories: 50,
        proteins: 3.6,
        carbs: 48,
        fats: 18,
    },
    {
        name: 'Salmon',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 267,
        proteins: 21.5,
        carbs: 0.1,
        fats: 20,
    },
    {
        name: 'Cocoa Powder Cadbury',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 416,
        proteins: 23,
        carbs: 14,
        fats: 21,
    },
    {
        name: 'Mozzarella',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 238,
        proteins: 17,
        carbs: 2,
        fats: 18,
    },
    {
        name: 'Sugar',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 400,
        proteins: 0.1,
        carbs: 100,
        fats: 0.1,
    },
    {
        name: 'Butter Salted',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 745,
        proteins: 0.6,
        carbs: 6,
        fats: 82,
    },
    {
        name: 'Swett Potatoes',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 86,
        proteins: 2,
        carbs: 17,
        fats: 0.1,
    },
    {
        name: 'Gyoza Chicken',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 155,
        proteins: 8.2,
        carbs: 20,
        fats: 44,
    },
    {
        name: 'Chocolate 70%',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 585,
        proteins: 8.7,
        carbs: 26.7,
        fats: 50,
    },
    {
        name: 'Chocolate Cadbury Classic',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 525,
        proteins: 4.3,
        carbs: 60,
        fats: 28,
    },
    {
        name: 'Houmous',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 349,
        proteins: 7,
        carbs: 9,
        fats: 31,
    },
    {
        name: 'ShortBread Biscuits',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 493,
        proteins: 5.2,
        carbs: 56,
        fats: 27,
    },
    {
        name: 'Cookies 4 Chocolate',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 476,
        proteins: 6,
        carbs: 66,
        fats: 20,
    },
    {
        name: 'Skittles',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 398,
        proteins: 0.1,
        carbs: 89,
        fats: 4.2,
    },
    {
        name: 'Olive Oil',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 123,
        proteins: 0.1,
        carbs: 0.1,
        fats: 13.7,
    },
    {
        name: 'Pizza Dough',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 205,
        proteins: 7.14,
        carbs: 39.4,
        fats: 1.3,
    },
    {
        name: 'Brown Sugar',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 398,
        proteins: 0.1,
        carbs: 100,
        fats: 0.1,
    },
    {
        name: 'Potatoes',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 99,
        proteins: 2.6,
        carbs: 20.6,
        fats: 0.1,
    },
    {
        name: 'Whey ON Double Chocolate',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 374,
        proteins: 76,
        carbs: 5.3,
        fats: 4.6,
    },
    {
        name: 'Whey ON Peanut Butter Chocolate',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 364,
        proteins: 74,
        carbs: 6.8,
        fats: 4.1,
    },
    {
        name: 'Ben & Jerrys Chocolate Fudge',
        unit: 'tub',
        gramsPerUnit: 408,
        calories: 1016,
        proteins: 17.5,
        carbs: 118,
        fats: 53,
    },
    {
        name: 'Pasta Rana Proscuitto Mozzarella',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 189,
        proteins: 8.8,
        carbs: 21,
        fats: 6.3,
    },
    {
        name: 'Pork Loin Steack',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 270,
        proteins: 27.2,
        carbs: 0.9,
        fats: 17.3,
    },
    {
        name: 'Minced Steack 5%',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 168,
        proteins: 31,
        carbs: 0.1,
        fats: 4.7,
    },
    {
        name: 'Bacon',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 266,
        proteins: 31,
        carbs: 0.8,
        fats: 16,
    },
    {
        name: 'Stilton Cheese',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 410,
        proteins: 23.7,
        carbs: 0.1,
        fats: 35,
    },
    {
        name: 'Cheddar Slices',
        unit: 'slice',
        gramsPerUnit: 24,
        calories: 100,
        proteins: 6.1,
        carbs: 0.1,
        fats: 8.4,
    },
    {
        name: 'Burger Buns',
        unit: 'bun',
        gramsPerUnit: 77,
        calories: 239,
        proteins: 6.8,
        carbs: 40,
        fats: 5.3,
    },
    {
        name: 'Babibel',
        unit: 'item',
        gramsPerUnit: 20,
        calories: 70,
        proteins: 4,
        carbs: 0.1,
        fats: 5,
    },
    {
        name: 'Cadbury Diary Milk',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 534,
        proteins: 7.3,
        carbs: 57,
        fats: 30,
    },
    {
        name: 'Jordans Chocolate Cereals',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 451,
        proteins: 9.2,
        carbs: 64.1,
        fats: 16.2,
    },
    {
        name: 'Kellog Choco Wheat',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 392,
        proteins: 10,
        carbs: 65,
        fats: 8,
    },
    {
        name: 'Edam',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 341,
        proteins: 27,
        carbs: 0.1,
        fats: 26,
    },
    {
        name: 'Sausisson',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 434,
        proteins: 32,
        carbs: 0.1,
        fats: 34,
    },
    {
        name: 'Chorizzo',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 406,
        proteins: 28,
        carbs: 1.4,
        fats: 32,
    },
    {
        name: 'Plain Flour',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 330,
        proteins: 9.9,
        carbs: 68,
        fats: 1.4,
    },
    {
        name: 'Guiness',
        unit: 'pint',
        gramsPerUnit: 475,
        calories: 167,
        proteins: 1.8,
        carbs: 14,
        fats: 0.1,
    },
    {
        name: 'Nutella',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 539,
        proteins: 6.3,
        carbs: 57,
        fats: 31,
    },
    {
        name: 'Ham slices',
        unit: 'slice',
        gramsPerUnit: 24,
        calories: 24,
        proteins: 4.6,
        carbs: 0.1,
        fats: 0.5,
    },
    {
        name: 'Philadelphia garlic',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 142,
        proteins: 7.2,
        carbs: 5.3,
        fats: 10,
    },
    {
        name: 'Seed Bread',
        unit: 'slice',
        gramsPerUnit: 46,
        calories: 134,
        proteins: 4.9,
        carbs: 18.2,
        fats: 4.1,
    },
    {
        name: 'Tortilla Wrap',
        unit: 'tortilla',
        gramsPerUnit: 50,
        calories: 181,
        proteins: 4.7,
        carbs: 33.9,
        fats: 2.6,
    },
    {
        name: 'Lindahls Kvarg Protein Yogurt',
        unit: '100g',
        gramsPerUnit: 150,
        calories: 83,
        proteins: 15,
        carbs: 5.1,
        fats: 0.3,
    },
    {
        name: 'Ice Lollies Orange',
        unit: 'lolly',
        gramsPerUnit: 75,
        calories: 63,
        proteins: 0.2,
        carbs: 14.8,
        fats: 0.2,
    },
    {
        name: 'Pizza Dough Eataly',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 318,
        proteins: 10,
        carbs: 65,
        fats: 0.9,
    },
    {
        name: 'Mochi Little Moons',
        unit: 'mochi',
        gramsPerUnit: 32,
        calories: 77,
        proteins: 0.5,
        carbs: 12,
        fats: 3,
    },
    {
        name: 'Ben & Jerrys Lighten Up Chocolate Cookie Dough',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 208,
        proteins: 4.7,
        carbs: 30,
        fats: 6.7,
    },
    {
        name: 'Eggs Noodles',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 140,
        proteins: 3.7,
        carbs: 25.7,
        fats: 2.3,
    },
    {
        name: 'Magnum Almond',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 327,
        proteins: 4.6,
        carbs: 31,
        fats: 20,
    },
    {
        name: 'Rolled Oats',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 374,
        proteins: 11,
        carbs: 60,
        fats: 8,
    },
    {
        name: 'Rough Oatcake',
        unit: 'oatcake',
        gramsPerUnit: 8,
        calories: 46,
        proteins: 1.1,
        carbs: 5.8,
        fats: 1.8,
    },
    {
        name: 'Frozen Raspberries',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 40,
        proteins: 1.4,
        carbs: 4.6,
        fats: 0.4,
    },
    {
        name: 'Biscoff Spread',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 584,
        proteins: 3,
        carbs: 57,
        fats: 38,
    },
    {
        name: 'Raspberry Jam',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 240,
        proteins: 1,
        carbs: 56,
        fats: 0.8,
    },
    {
        name: 'Apple',
        unit: 'apple',
        gramsPerUnit: 180,
        calories: 78,
        proteins: 1,
        carbs: 17,
        fats: 1,
    },
    {
        name: 'Pear',
        unit: 'item',
        gramsPerUnit: 150,
        calories: 47,
        proteins: 0.1,
        carbs: 10,
        fats: 0.1,
    },
    {
        name: 'Van Houten',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 379,
        proteins: 20,
        carbs: 11,
        fats: 21,
    },
    {
        name: 'Nairns Oat Chocolate Biscuit',
        unit: 'biscuit',
        gramsPerUnit: 10,
        calories: 45,
        proteins: 0.8,
        carbs: 6.4,
        fats: 1.7,
    },
    {
        name: 'Spaguetti Whole',
        unit: '100g',
        gramsPerUnit: 100,
        calories: 164,
        proteins: 5.5,
        carbs: 33.2,
        fats: 0.7,
    },
    {
        name: 'Ben & Jerrys Phish Food',
        unit: 'tub',
        gramsPerUnit: 399,
        calories: 1089,
        proteins: 14.4,
        carbs: 139.6,
        fats: 52,
    },
]