import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import * as React from "react"
import { ThemeProvider } from "@/components/theme-provider"
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-2 items-center justify-center size-full flex">
          <div className="rounded-[0.5rem] border bg-background shadow-md flex size-full lg:size-11/12 xl:size-10/12">
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
            <SideBar />
            {children}
            </ThemeProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
